### PR TITLE
Restoring the old Kepware interface while the new one gets more thoroughly tested

### PR DESCRIPTION
**Pull request by dangond-ptc**

### CODE REVIEW

**Review by hobinjk-ptc — APPROVED** [review]
Looks good as a stopgap measure

**Review by benptc — APPROVED** [review]

**Comment by benptc** [comment]
Should we merge this or are we waiting for a review from @valentinptc?

**Comment by dangond-ptc** [comment]
It should be good to go, so if you think it's fine we can merge.

**Comment by benptc** [comment]
Ok, let's merge it

**Pull request merged**
